swagger: "2.0"
info:
    description: "APIs"
    version: "1.0.0"
    title: "APIs"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
    - "http"
consumes:
    - "application/json"
produces:
    - "application/json"
paths:
    /users:
        get:
            summary: "Get list of users"
            parameters:
                - name: "limit"
                  in: "query"
                  type: "integer"
                  required: false
                  description: "Limit number of results"
                - name: "offset"
                  in: "query"
                  type: "integer"
                  required: false
                  description: "Offset for pagination"
            responses:
                "200":
                    description: "List of users retrieved successfully"
    /users/{id}:
        get:
            summary: "Get user by ID"
            parameters:
                - name: "id"
                  in: "path"
                  type: "integer"
                  required: true
                  description: "ID of user to retrieve"
            responses:
                "200":
                    description: "User retrieved successfully"
        put:
            summary: "Update user by ID"
            parameters:
                - name: "id"
                  in: "path"
                  type: "integer"
                  required: true
                  description: "ID of user to update"
                - name: "body"
                  in: "body"
                  required: true
                  schema: {}
            responses:
                "200":
                    description: "User updated successfully"
                "404":
                    description: "User not found"
        delete:
            summary: "Delete user by ID"
            parameters:
                - name: "id"
                  in: "path"
                  type: "integer"
                  required: true
                  description: "ID of user to delete"
            responses:
                "204":
                    description: "User deleted successfully"
                "404":
                    description: "User not found"
    /users/{id}/active:
        patch:
            summary: "Activate user by ID"
            parameters:
                - name: "id"
                  in: "path"
                  type: "integer"
                  required: true
                  description: "ID of user to activate"
                - name: "body"
                  in: "body"
                  required: true
                  schema: {}
            responses:
                "200":
                    description: "User activated successfully"
                "404":
                    description: "User not found"
    /users/{id}/inactive:
        patch:
            summary: "Inactivate user by ID"
            parameters:
                - name: "id"
                  in: "path"
                  type: "integer"
                  required: true
                  description: "ID of user to inactive"
                - name: "body"
                  in: "body"
                  required: true
                  schema: {}
            responses:
                "200":
                    description: "User inactivated "
                "404":
                    description: "User not found"
